export const FETCH_ALL_TODOS = "FETCH_ALL_TODOS";
export const FETCH_ALL_TODOS_SUCCESS = "FETCH_ALL_TODOS_SUCCESS";
export const FETCH_ALL_TODOS_FAIL = "FETCH_ALL_TODOS_FAIL";

export const SUBMIT_TODO = "SUBMIT_TODO";
export const SUBMIT_TODO_SUCCESS = "SUBMIT_TODO_SUCCESS";
export const SUBMIT_TODO_FAIL = "SUBMIT_TODO_FAIL";

export const TOGGLE_IS_COMPLETED = "TOGGLE_IS_COMPLETED";
export const TOGGLE_IS_COMPLETED_SUCCESS = "TOGGLE_IS_COMPLETED_SUCCESS";
export const TOGGLE_IS_COMPLETED_FAIL = "TOGGLE_IS_COMPLETED_FAIL";

export const TOGGLE_IS_DELETED = "TOGGLE_IS_DELETED";
export const TOGGLE_IS_DELETED_SUCCESS = "TOGGLE_IS_DELETED_SUCCESS";
export const TOGGLE_IS_DELETED_FAIL = "TOGGLE_IS_DELETED_FAIL";

export const CHANGE_FILTER = "CHANGE_FILTER";
