// fetch
// all
export const FETCH_ALL_TODOS = "FETCH_ALL_TODOS";
export const FETCH_ALL_TODOS_SUCCESS = "FETCH_ALL_TODOS_SUCCESS";
export const FETCH_ALL_TODOS_FAIL = "FETCH_ALL_TODOS_FAIL";
// submit
export const SUBMIT_TODO = "SUBMIT_TODO";
export const SUBMIT_TODO_SUCCESS = "SUBMIT_TODO_SUCCESS";
export const SUBMIT_TODO_FAIL = "SUBMIT_TODO_FAIL";
// toggle
// is completed
export const TOGGLE_IS_COMPLETED = "TOGGLE_IS_COMPLETED";
export const TOGGLE_IS_COMPLETED_SUCCESS = "TOGGLE_IS_COMPLETED_SUCCESS";
export const TOGGLE_IS_COMPLETED_FAIL = "TOGGLE_IS_COMPLETED_FAIL";
// is deleted
export const TOGGLE_IS_DELETED = "TOGGLE_IS_DELETED";
export const TOGGLE_IS_DELETED_SUCCESS = "TOGGLE_IS_DELETED_SUCCESS";
export const TOGGLE_IS_DELETED_FAIL = "TOGGLE_IS_DELETED_FAIL";
// change
// search query
export const CHANGE_SEARCH_QUERY = "CHANGE_SEARCH_QUERY";
// filter
export const CHANGE_FILTER = "CHANGE_FILTER";
