const ACTION_TYPES = {
  FETCH_ALL_TODOS: "FETCH_ALL_TODOS",
  FETCH_ALL_TODOS_SUCCESS: "FETCH_ALL_TODOS_SUCCESS",
  FETCH_ALL_TODOS_FAIL: "FETCH_ALL_TODOS_FAIL",

  SUBMIT_TODO: "SUBMIT_TODO",
  SUBMIT_TODO_SUCCESS: "SUBMIT_TODO_SUCCESS",
  SUBMIT_TODO_FAIL: "SUBMIT_TODO_FAIL",

  TOGGLE_IS_COMPLETED: "TOGGLE_IS_COMPLETED",
  TOGGLE_IS_COMPLETED_SUCCESS: "TOGGLE_IS_COMPLETED_SUCCESS",
  TOGGLE_IS_COMPLETED_FAIL: "TOGGLE_IS_COMPLETED_FAIL",

  TOGGLE_IS_DELETED: "TOGGLE_IS_DELETED",
  TOGGLE_IS_DELETED_SUCCESS: "TOGGLE_IS_DELETED_SUCCESS",
  TOGGLE_IS_DELETED_FAIL: "TOGGLE_IS_DELETED_FAIL",

  CHANGE_SEARCH_QUERY: "CHANGE_SEARCH_QUERY",

  CHANGE_SELECTED_FILTER: "CHANGE_SELECTED_FILTER",
};

export default ACTION_TYPES;
